POST http://localhost:8050/api/library
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjg4MTU5ODg4LCJleHAiOjE2ODg3NjQ2ODh9.JhKQR3822bBKDuqqsuijyK0Lthk84ogId1Fgth_rLbM

{
    "name" : "Del Norte Libreria",
    "location" : "San Isidro, Catamarca",
    "phone" : "5493834212333"
}

