POST http://localhost:8050/api/library
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjg4MjY3NjEzLCJleHAiOjE2ODg4NzI0MTN9.r-2khm__O2Vd9XiSDrfIcaEX74hEZcfa38DvnPMgQCE

{
    "name" : "Del Norte Libreria",
    "location" : "San Isidro, Catamarca",
    "phone" : "5493834212333"
}

