POST http://localhost:8050/api/book
Content-Type : application/json


{
    "isbn" : 100,
    "title" : "Don Quijote de la Mancha",
    "author" : "Miguel de Cervantes Saavedra",
    "year" : "1605",
    "libraryId": 1
}

###



###



