PUT http://localhost:8050/api/book/1
Content-Type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjg4MjY3NjEzLCJleHAiOjE2ODg4NzI0MTN9.r-2khm__O2Vd9XiSDrfIcaEX74hEZcfa38DvnPMgQCE

{
    "title" : "Romeo y Julieta",
    "author" : "William Shakespeare",
    "year" : "1597"
}